### ISSUE TITLE
Babel version & config and other updates

### ISSUE THREAD

**Issue by detroitenglish** [anderly/cloudflare-worker-routing#1]
Thanks for the shout-out 😎

Wanted to give you quick heads-up:

- Babel 7 is still technically in beta... I use it in prod, but I'm crazy like that
- `babel@polyfill` and `babel@preset-env` are not applied in the build-step. You'll need to pass your entry script through `babel@polyfill`, and use modules rules with `babel-loader` to do so 
- `scripts/deploy.js` error handling messages are 💩

I just pushed an [update to my own cf-worker](https://github.com/detroitenglish/pw-pwnage-cfworker/commits?author=detroitenglish&since=2018-07-31T22:00:00Z&until=2018-08-15T22:00:00Z) with fixes. Also changed the browserslist target to Chrome >= 57.

**Comment by anderly** [comment]
Thanks Dave!

If this is simply running in a CloudFlare worker and not in a browser, I don't think I even need babel@polyfill or maybe even babel@preset-env. Thoughts?

Thanks for the heads up on deploy and the link to your updates.

**Comment by detroitenglish** [comment]
Dug into a bit and learned that Cloudflare always keeps the worker runtime [in line with the latest Chrome](https://developers.cloudflare.com/workers/reference/) version.  So now babel-polyfill indeed seems unnecessary.

I'm definitely keeping `babel@preset-env` though; with Babel 7 it's _so_ much nicer to use e.g. `import` and object-rest-spread and never worry about installing plugins or tooling.

**Comment by anderly** [comment]
10-4. On that link it says "This means you can safely use latest JavaScript features, with no need for “transpilers”. So, I wonder if we really need babel at all? Will `import` not work without it. rest and spread operators appear to work without needing babel. However, I did see your use of the closure elimination plugin which is nice. For now, I've synced it up with your changes but I'm gonna try removing babel completely and see what, if anything, breaks.

**Comment by detroitenglish** [comment]
Transpilation of the worker script might not be necessary, but I for one 'never leave home' without Babel. Mostly just to save me from myself; I can't be bothered to keep up with browser compatibilty and what APIs need polyfilling where. Also my IDE would go bananas. Curious if/how Husky `precommit` linting will work without Babel installed...

Another thing I learned that doesn't seem to be documented: Cloudflare actually validates uploaded worker scripts on their end, and will reject invalid scripts with a 400 response. So `esprima` validation isn't necessary  in the deployment script.

Pushed some [minor updates](https://github.com/detroitenglish/pw-pwnage-cfworker/commits?author=detroitenglish&since=2018-08-15T22:00:00Z&until=2018-08-16T22:00:00Z) removing esprima and tweaking some tooling config, nothing drastic.

**Comment by anderly** [comment]
Cool, thanks. Yes, I noticed they validate on their end and reject if invalid, so I had removed the esprima package as well.

I'm already using this boilerplate as a very lightweight edge oauth proxy which is working nicely and I don't have to worry about being the central bottleneck standing up my own oauth proxy server(s).
